apiVersion: v1
kind: Service
metadata:
  name: front-service
  namespace: nagashima_ns
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deploy
  namespace: nagashima_ns
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nagashima_ns
        image: 819724587289.dkr.ecr.ap-northeast-1.amazonaws.com/nagashima_repo
        ports:
        - containerPort: 80
